### ISSUE TITLE
did you get banned?

### ISSUE THREAD

**Issue by luanon404** [Z4ee/StarRail-S-GC#12]
I have no experience with this, so I want to ask you if the publisher knows when I speed up the game? i captured requests, but i dont see anything about speed data, can you give me some suggest?

**Comment by Suntz246** [comment]
The following is just my personal opinion

This game manufacturer does not have very advanced anti-cheating methods, don't worry, a lot of your data is uploaded to the server after the client calculates, which does not include acceleration data

I have been using this project since it was released, and I have not received any ban information

**Comment by luanon404** [comment]
Thank you for your advice. Perhaps it's okay to play around with it a little bit :P
